services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/core
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: WebUsers
      MYSQL_USER: admin
      MYSQL_PASSWORD: 2610
      MYSQL_ROOT_PASSWORD: 2610
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql_data:

